### ISSUE TITLE
[BUG] Game crashes when installing version 0.5.4 and YACL.

### ISSUE THREAD

**Issue by LittleCircleOO** [MisterJulsen/Create-Train-Navigator#29] opened 2024-07-06 07:14 UTC
**Version:**
 - Minecraft Version: 1.20.1
 - Fabric Version: Fabric Loader 0.15.11
 - Mod Version 0.5.4

**Describe the bug**
The game crashs when installed with [yacl](https://modrinth.com/mod/yacl).
This issue is not reproduced in 0.5.3.

**To Reproduce**
Install this mod (0.5.4) and yacl (3.5.0), then start the game.

**Expected behavior**
The game starts normally.

**Additional context**
Related feedback: https://github.com/isXander/YetAnotherConfigLib/issues/192

**Comment by MisterJulsen** [comment] 2024-07-06 11:07
Thanks for your report! The bug is caused by DragonLib 2.1.13, which is integrated into CRN. I am trying to find the cause of the problem and try to solve it.

**Comment by bangetto** [comment] 2024-07-07 12:40
hm, this is probably the cause of mine issue too #27

**Comment by MisterJulsen** [comment] 2024-07-13 12:22
Should be fixed with the latest update for CRN on 1.20.1

**Closed as completed by MisterJulsen** 2024-07-13 12:22 UTC
Labels: bug
